
POST http://localhost:3000/user
content-type: application/json

{
    "firstName": "testName", 
    "lastName": "TestLastname", 
    "age": 5
}
###

GET http://localhost:3000/users

###

DELETE  http://localhost:3000/user/3

###
PUT  http://localhost:3000/user/1
content-type: application/json

{
    "firstName": "Lars3", 
    "lastName": "Jam2", 
    "age": 24
}
